### ISSUE TITLE
java.lang.illegalStateException during connection

### ISSUE THREAD

**Issue by SteveClement** [cybertier/mispbump#11]
I compiled it from source (with Android Studio) and have the same issues as with the latest release.

```
Expected a string but was BEGIN_ARRAY at line 14 column 34 path $.Organisation.restricted_to_domain
```

The reason being that my instance returns:

```
   'restricted_to_domain': ['circl.lu', 'admin.test'],
```

In an organisation you can have a list of domains.

Thus your code wants to consider that as an Array and not a String.

Changing: https://github.com/cybertier/mispbump/blob/5e95c53670e2e7b1c598d43a670370f3e19eeffb/app/src/main/java/lu/circl/mispbump/models/restModels/Organisation.java#L19

To:

```
    public String[] restricted_to_domain;
```

Makes it "work" not sure what the overall impact might be.

**Comment by felixpk** [comment]
Thank you for your feedback! I will check it

**Comment by felixpk** [comment]
@SteveClement could tell me what version of MISP you are using?
I haven't set the "restricted_to_domain" option and in my case it gives me an empty string.
I don't even know how to set this option to be honest (from the web interface).
If this is an inconsistency in the API we will need to file an issue in the MISP repo.

**Comment by SteveClement** [comment]
Go to the Organisations index:

    Administration -> List Organisations
    ($BASEURL/organisations/index)

And edit your orga ($BASEURL/admin/organisations/edit/1)

Here you will find:

    "Bind user accounts to domains (line separated)"

I use latest v2.4.111

**Comment by felixpk** [comment]
Opened an [Issue](https://github.com/MISP/MISP/issues/4928#issue-471654317). Again, thanks for your feedback!

**Comment by SteveClement** [comment]
> Opened an [Issue](https://github.com/MISP/MISP/issues/4928#issue-471654317). Again, thanks for your feedback!
> 
> The development branch now has a temporary "fix". It still wont work with empty `restricted_to_domain` but in your case it should be fine.

Thank you for having indirectly discovered this bug ;)

We shall fix it asap.
