### ISSUE TITLE
mispbump under MISP Project?

### ISSUE THREAD

**Issue by adulau** [cybertier/mispbump#13]
Hi Felix,

Thanks a lot for your hard work!

I invited you to the MISP Project organisation to manage (as admin) the [mispbump](https://github.com/MISP/misp-bump) repository. If you feel comfortable with this, feel free to push on that repository and maintain it as you wish. 

Thanks again.

Cheers

**Comment by felixpk** [comment]
Hi Alexandre,

Thank you very much, it‘s nice to see this becoming a part of MISP.
I will transfer the project as soon as possible!

Best regards

**Comment by adulau** [comment]
Great! See you very soon.
